### PR TITLE
New tuning from 13 MHz to 86 MHz.

### PR DESCRIPTION
**Pull request by yupinghuang**
**WARNING** since some of the config entries in this repos are duplicated in the caltech-lwa repo, someone who did `cold_start_from_config` with the F engine API will probably load the wrong config. https://github.com/realtimeradio/caltech-lwa/blob/master/control_sw/config/lwa_corr_config.yaml

And since the fengine config in this repo now looks slightly different from the caltech-lwa one due to the recent dr mapping update....it's complicated

## Tests
- [x] subbands are contiguous
- [x] subbands have the right width
- [x] data recorder records the right data
```
In [10]: for v in config['xengines']['chans'].values():
    ...:     print(v[0], v[1]-v[0])
    ...: 
560 96
656 96
752 96
848 96
944 96
1040 96
1136 96
1232 96
1328 96
1424 96
1520 96
1616 96
1712 96
1808 96
1904 96
2000 96
2096 96
2192 96
2288 96
2384 96
2480 96
2576 96
2672 96
2768 96
2864 96
2960 96
3056 96
3152 96
3248 96
3344 96
3440 96
3536 96
```
On calim
```
(base) [pipeline@lwacalim01 ~]$ pdsh -w lwacalim[01-08] 'ls -lstra /data0?/slow/ | grep ms |tail -2' | sort -k1,1 -n
lwacalim01:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_13MHz.ms
lwacalim01:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_18MHz.ms
lwacalim02:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_23MHz.ms
lwacalim02:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_27MHz.ms
lwacalim03:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_32MHz.ms
lwacalim03:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_36MHz.ms
lwacalim04:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_41MHz.ms
lwacalim04:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_46MHz.ms
lwacalim05:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_50MHz.ms
lwacalim05:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_55MHz.ms
lwacalim06:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_59MHz.ms
lwacalim06:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_64MHz.ms
lwacalim07:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_69MHz.ms
lwacalim07:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_73MHz.ms
lwacalim08:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_78MHz.ms
lwacalim08:    9 drwxr-xr-x.    15 pipeline pipeline    20 Feb 15 17:05 20230215_170510_82MHz.ms
```
```

### CODE REVIEW

**Comment by jack-h** [comment]
I consider configs in the `caltech-lwa` repo to be for testing only, so I think no-one should be using them.

**Comment by jack-h** [comment]
Can you tell (using [preferably] test vectors or [less ideal] RFI) that the shift is really seen in data?

**Review by jack-h — APPROVED** [review]

**Review by caseyjlaw — APPROVED** [review]

**Comment by yupinghuang** [comment]
I changed Casey's control.py to enable the test vector then ran initialized. And the visibility coming out of the lowest subband in the data recorder looks like this (autocorrs only)
Screenshot from 2023-02-16 14-15-48

The horizontal spread is by SNAP boards. I looked at the bottom dots near chans 60-100.

This....doesn't look right?

```
diff --git a/mnc/control.py b/mnc/control.py
index b16cf57..5c978fd 100644
--- a/mnc/control.py
+++ b/mnc/control.py
@@ -163,13 +163,14 @@ class Controller():
                 source_port = localconf['source_port']
 
                 f.cold_start(program = program, initialize = initialize, fft_shift=fft_shift,
-                             #test_vectors = test_vectors, sync = sync,
+                             test_vectors = True,
+#                             sync = sync,
 #                             sw_sync = sw_sync, enable_eth = enable_eth,
                              chans_per_packet = chans_per_packet,
                              first_stand_index = first_stand_index, nstand = nstand, macs = macs, source_ip = source_ip,
                              source_port = source_port, dests = dests)
                 
-                f.print_status_all()
+#                f.print_status_all()
```

**Comment by yupinghuang** [comment]
Tried again just now.
Screenshot from 2023-02-16 19-17-15

First nadir is at channel 15 and the global peak at channel 88.

This is the first subband.

Still confused...

**Comment by jack-h** [comment]
I think the secret knowledge you are missing is what the test vectors
actually are.
The vectors loaded are a frequency ramp --
https://github.com/realtimeradio/caltech-lwa/blob/fc631ffe306cab6bd3c927ccceb22da73df801e5/control_sw/src/snap2_fengine.py#L672
-- but there are only 8-bits per sample (interpretted as 4-bit real + 4-bit
imag), and 4096 frequency channels, so things wrap in fun ways.

To get the complex-valued correlator inputs based on the test pattern:

```
def build_test_vectors():
    tv = np.arange(4096, dtype=int)
    tv = tv % 256 # 8 bit values
    tv_real = (tv >> 4) & 0xf # 4-bit real
    tv_imag = (tv & 0xf) # 4-bit imag
    tv_real[tv_real>7] -= 16 # convert to 2's complement signed

    tv_imag[tv_imag>7] -= 16 # convert to 2's complement signed

    return tv_real + 1j*tv_imag
```

Then the correlator output (assuming accumulation length is divided out)
for any baseline should be:

```
x = build_test_vectors()
plot(np.abs(x)**2, '-o')
```

Assuming you are plotting 192 channels starting at 560:
```
x = build_test_vectors()
plot(np.abs(x[560:560+192])**2, '-o')
```
yields
[image: image.png]


So at first glance, I think the chaos you're seeing might equal success!

**Comment by jack-h** [comment]
I think the secret knowledge you are missing is what the test vectors actually are.
The vectors loaded are a frequency ramp --  https://github.com/realtimeradio/caltech-lwa/blob/fc631ffe306cab6bd3c927ccceb22da73df801e5/control_sw/src/snap2_fengine.py#L672 -- but there are only 8-bits per sample (interpretted as 4-bit real + 4-bit imag), and 4096 frequency channels, so things wrap in fun ways.

To get the complex-valued correlator inputs based on the test pattern:

```
def build_test_vectors():
    tv = np.arange(4096, dtype=int)
    tv = tv % 256 # 8 bit values
    tv_real = (tv >> 4) & 0xf # 4-bit real
    tv_imag = (tv & 0xf) # 4-bit imag
    tv_real[tv_real>7] -= 16 # convert to 2's complement signed

    tv_imag[tv_imag>7] -= 16 # convert to 2's complement signed

    return tv_real + 1j*tv_imag                               
```

Then the correlator output (assuming accumulation length is divided out) for any baseline should be:

```
x = build_test_vectors()
plot(np.abs(x)**2, '-o')
```

Assuming you are plotting 192 channels starting at 560:
```
x = build_test_vectors()
plot(np.abs(x[560:560+192])**2, '-o')
```
yields

image

So at first glance, I think the chaos you're seeing might equal success!

**Pull request merged**
