### PR TITLE
Add Fast visibility selection by LWA antenna name

### PR DESCRIPTION
**Pull request by jack-h**
- Add `fast_vis_ants` config file field, which should contain a list of LWA names
- When fast visibility recording is enabled update all pipelines with selected antennas
- Update default configuration file to enable fast visibilities for DG's suggested antennas

### CODE REVIEW

**Review by caseyjlaw — APPROVED** [review]

**Comment by caseyjlaw** [comment]
This looks great. I'll try an observing test today.

**Comment by caseyjlaw** [comment]
I am testing the fast visibility observing now that the configuration file and code are in place.
I am seeing the data recorders instantly get overwhelmedm, even after restarting them. I suspect something about the x-engines is not set correctly.

Running pipeline control manually, I can do:
```
> fast_vis_out   # created fast corr pairs
array([[[71,  0],
        [71,  0]],
...

> con.pcontroller.pipelines[0].corr_subsel.set_baseline_select(fast_vis_out)
'0'

> p0 = con.pcontroller.pipelines[0]
> p0.corr_subsel.get_baseline_select()
[nothing returned]

> p0.corr_subsel.update_is_pending()   # saw this method and gave it a try
[nothing returned]
```

Questions:
- if the data recorders are behind by 10000% (or something huge), how can we pin that to an x-eng vs dr issue?
- should the "get" method show that a subset of baselines are used?

**Comment by jack-h** [comment]
So, I take back my earlier comment. 
Running the default config with recorders `['drvs', 'drvf']` (note that currently just the fast on its own doesn't work since the slow recorder configures upstream correlator parameters) I saw no fast output out of `lwa-gpu01`. Nothing shown in `like_bmon` or `tcpdump`.

If I change `corr_subsel.set_baseline_sel(...)` to be a no-op, the output appears as expected. I'm not sure what the issue is here -- something about the selection choice must be crashing the subselection block in the pipeline, but if that is what is happening, there is no evidence in the logs.

I'll look into this more, but in the meantime perhaps it is useful to try to make the fast recorder work without any selection loaded to at least verify/debug the data capture side.

**Comment by jack-h** [comment]
issue #351 fixed

**Pull request merged**
